const Router = require('express')
const router = new Router()

const contentController = require('../controller/contentController')
const userController = require('../controller/userController')
const coupleController = require('../controller/coupleController')
const commentController = require('../controller/commentController')
const statsController = require('../controller/statsController')

router.get('/contents', contentController.getContent)
router.get('/contents/together/:userId/:partnerId', contentController.getContentTogether)
router.get('/contents/user/:userId', contentController.getContentByUserId)
router.get('/content/id/:id', contentController.getContentById)
router.put('/update/content', contentController.updateContentById)
router.post('/create/content', contentController.createContent)
router.delete('/delete/content', contentController.deleteContent)

router.get('/users', userController.getUsers)
router.get('/user/id/:id', userController.getUserById)
router.post('/auth/user', userController.userAuth)
router.put('/update/user', userController.updateUser)
router.post('/create/user', userController.createUser)
router.delete('/delete/user', userController.deleteUser)
router.put('/user/generate-token', userController.generateToken)
router.put('/user/refresh-token', userController.refreshToken)
router.put('/user/join-couple', userController.joinCouple)

router.get('/couples', coupleController.getCouples)
router.get('/couple/id/:id', coupleController.getCoupleById)
router.put('/update/couple', coupleController.updateCouple)
router.post('/create/couple', coupleController.createCouple)
router.delete('/delete/couple', coupleController.deleteCouple)

router.get('/comments', commentController.getComments)
router.get('/comment/id/:id', commentController.getCommentById)
router.get('/comments/content/:contentId', commentController.getCommentsByContentId)
router.put('/update/comment', commentController.updateComment)
router.post('/create/comment', commentController.createComment)
router.delete('/delete/comment', commentController.deleteComment)

router.get('/stats/categories/:userId/:partnerId', statsController.getCategoryStats)
router.get('/stats/monthly/:userId/:partnerId', statsController.getMonthlyStats)
router.get('/stats/status/:userId/:partnerId', statsController.getStatusStats)
router.get('/stats/completion/:userId/:partnerId', statsController.getCompletionRateByCategory)

module.exports = router;